package com.jmarket.notification.dto;

public enum NotificationType {
    AUCTION_OUTBID,
    AUCTION_OUTBID_LOST,
    AUCTION_WON,
    AUCTION_SOLD,
    TRADE_REQUESTED,
    TRADE_COMPLETED,
    TRADE_REVIEW_REQUESTED,
    REVIEW_RECEIVED,
    REPORT_RESOLVED,
    USER_RESTRICTED,
    MILEAGE_WITHDRAWAL_REQUESTED,
    CHAT_MESSAGE
}
